name: Circuler Server CI

on:
  pull_request:
    branches: [ main ]  # 또는 dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Tests
        run: |
          mkdir -p src/test/resources

          cat <<EOF > src/test/resources/application.yml
          spring:
            datasource:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: ${{ secrets.DB_URL }}
              username: ${{ secrets.DB_USERNAME }}
              password: ${{ secrets.DB_PASSWORD }}
            jpa:
              hibernate:
                ddl-auto: update
              properties:
                hibernate:
                  format_sql: true
                  use_sql_comments: true
                  dialect: org.hibernate.dialect.MySQL8Dialect

            redis:
              host: ${{ secrets.REDIS_HOST }}
              port: ${{ secrets.REDIS_PORT }}

            security:
              oauth2:
                client:
                  registration:
                    google:
                      client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
                      client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                      redirect-uri: ${{ secrets.GOOGLE_REDIRECT_URI }}
                      scope:
                        - email
                        - profile

          jwt:
            secret: ${{ secrets.JWT_SECRET }}
          EOF

          chmod +x ./gradlew
          ./gradlew test
        working-directory: ./server
