name: Circuler Server CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew test
        working-directory: ./server
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SPRING_REDIS_HOST: ${{ secrets.REDIS_HOST }}
          SPRING_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CIRCULO_DOMAIN: ${{ secrets.CIRCULO_DOMAIN }}
          VERTEX_PROJECT_ID: ${{ secrets.VERTEX_PROJECT_ID }}
          VERTEX_ENDPOINT_ID: ${{ secrets.VERTEX_ENDPOINT_ID }}