name: Circuler Server CD

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 테스트 용도

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to server
        run: |
          scp server/docker-compose.yml ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/docker-compose.yml

      - name: Create .env on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" > /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_REDIS_HOST=${{ secrets.REDIS_HOST }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_REDIS_PORT=${{ secrets.REDIS_PORT }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "VERTEX_PROJECT_ID=${{ secrets.VERTEX_PROJECT_ID }}" >> /home/${{ secrets.VM_USER }}/.env
            echo "VERTEX_ENDPOINT_ID=${{ secrets.VERTEX_ENDPOINT_ID }}" >> /home/${{ secrets.VM_USER }}/.env

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull mandar2n/circulo:latest
            docker tag mandar2n/circulo:latest circulo_spring
            docker stop circulo || true
            cd /home/${{ secrets.VM_USER }}
            docker-compose --env-file .env -f docker-compose.yml up -d
